export const Theme = {
  colors:{
    black: '#121315',
    gray: '#1C2025',
    green: '#2FEBD2',
    green100: '#26857B',
  },
  img:{
    log: require('../assets/log.png'),
    back: require('../assets/back.png'),
    pass: require('../assets/pass.png'),
    mail: require('../assets/mail.png'),
    home: require('../assets/home.png'),
    tran: require('../assets/tranc.png'),
    lamp: require('../assets/lamp.png'),
    lmapg: require('../assets/LampG.png'),
    sens: require('../assets/sens.png'),
    seg: require('../assets/seg.png'),
    backG: require('../assets/back1.png'),
    ledA: require('../assets/ledA.png'),
    ledP: require('../assets/ledP.png'),
    person: require('../assets/person.png'),
    ajuda: require('../assets/aju.png'),
    deslog: require('../assets/des.png'),
    termos: require('../assets/terms.png'),
    set: require('../assets/set.png'),
    dado: require('../assets/dado.png'),
    wif: require('../assets/wifi.png'),
  }
}
